#发布环境
server:
  port: 8099



spring:
  datasource:
    username: root
    password: 981028
    url: jdbc:mysql://localhost:3306/shuliu?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false

  messages:
    basename: i18n.login

swagger:
  show: false


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0