#生产环境
server:
  port: 8088
  tomcat:
    max-http-form-post-size: -1


spring:
  datasource:
    username: root
    password: 990324
    url: jdbc:mysql://localhost:3309/shuliu?serverTimezone=GMT&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf-8

    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10GB

  redis:
    host: 127.0.0.1
    port: 6379

  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false

  messages:
    basename: i18n.login
  mvc:
    static-path-pattern: /**

swagger:
  show: true

#  E:/images/
#  /usr/images/
file-save-path: E:/images/


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

interceptorconfig:
  excludePathPatterns:
    - /swagger-ui.html
    - /webjars/**
    - /swagger-resources/**
    - /frontLogin
    - /backgroundLogin
    - /error
    - /
    - /csrf







